// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type List struct {
	ID          int64
	Name        string
	Description string
}

type Task struct {
	ID          int64
	ListID      int64
	Description string
	CreatedAt   pgtype.Timestamp
	CompletedAt pgtype.Timestamp
}
